'''
Sample generated resolver base classes.


note: Generated by:

-- app_config.py --
class AppConfig(BaseAppConfig[AppContext]):
    pass

app_config = AppConfig()

app_config.add_query(User)
app_config.add_mutation(add_user)

-- generate_resolvers.py --

app_config.generate_resolver_bases('./__generated_resolver_bases')

-----------------------------------
next step: implement base classes,

from .__generated_resolver_bases.next_step import NextStep
from .__generated_resolver_bases.base_classes import (
    ...
)

class PostsResolver(BasePostsResolver):
  resolve():

NextStep(
  posts_resolver = PostsResolver,
  add_post_mutation = AddPostMutation,
)

'''